# Site settings
title: Erica's Tech Blog
email: me@erica.tech
description: > # this means to ignore newlines until "baseurl:"
  Learn. Build. Discuss.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
twitter_username: 
github_username:  esosa0

# Build settings
markdown: kramdown

sass:
  # loading path from site root
  # default to _sass
  load_paths:
    - _sass
    - bower_components/bootstrap-sass/assets/stylesheets

  # style : nested (default), compact, compressed, expanded
  #         :nested, :compact, :compressed, :expanded also works
  # see http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style
  # on a typical twitter bootstrap stats are :
  # nested 138,7kB, compact 129,1kB, expanded 135,9 kB, compressed 122,4 kB
  style: compressed

gems:
  - jemoji
